version: 0.7.{build}
os: Windows Server 2012 R2
artifacts:
  - path: KSFramework-$(appveyor_build_version).zip
    name: KSFramework-$(appveyor_build_version)
build_script:
- cmd: git submodule init
- cmd: git submodule update
- cmd: Install.bat
after_build:
  - cmd: 7z a KSFramework-$(appveyor_build_version).zip KSFramework/
test: off
#deploy:
#- provider: Environment
#  name: Github
#  release: KSFramework-$(appveyor_build_version)
  #on:
  #  branch: master                # release from master branch only
  #  appveyor_repo_tag: true       # deploy on tag push only
